name: .NET Core

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore 
      working-directory: ./src/vssummit
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./src/vssummit
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: ./src/vssummit
    
    - name: Dotnet Publish
      run: dotnet publish --configuration Release -o netcore 
      working-directory: ./src/vssummit
    
    - uses: actions/upload-artifact@v2
      with:
        name: vssummit
        path: ./src/vssummit/netcore

    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: vssummit2020 
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} 
        package: './src/vssummit/netcore'

